name: 'ecma-402'

on: [pull_request, push]

jobs:
  build:
    name: 'build & lint ecmarkup'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - uses: ljharb/actions/node/run@main
        name: 'npm install && npm run build-master'
        with:
          node-version: lts/*
          command: 'build-master'
