name: 'deploy github pages'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: 'deploy github pages'
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'tc39/ecma402' }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: 'build-main'
        uses: ljharb/actions/node/run@main
        with:
          node-version: lts/*
          shell-command: |
            npm run build-only
      - name: Checkout RC 🛎️ 🛎️
        uses: actions/checkout@v2
        with:
          ref: 'es2021'
          clean: false
      - name: mdkir rc folder
        run: mkdir out/2021
      - name: copy images
        run: cp -R img "out/2021"
      - name: build rc
        uses: ljharb/actions/node/run@main
        with:
          node-version: lts/*
          shell-command: |
            ecmarkup --verbose spec/index.html out/2021/index.html --css out/2021/ecmarkup.css --js out/2021/ecmarkup.js
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: out
